### ISSUE TITLE
Current scale on DPS5020

### ISSUE THREAD

**Issue by austrisv** [opensolarproject/OSPController#23]
outCurr_, limitCurr_ and setCurrent needs scale adjustment for DPS5020 (/1000 for DPS5005, but /100 for DPS5020)

**Comment by t413** [comment]
Support for this added in aa0a3623ca77cc199dca925e6ccf48833cfe2f6d! Full tested DPS5020 support is in anything past `v2.0-22-gc655a1d-20210520`
