### ISSUE TITLE
DPS5020 can not power off

### ISSUE THREAD

**Issue by austrisv** [opensolarproject/OSPController#24]
OSP running on esp, all good. If I send outputEN=0 command, can see power icon turning red on the dps, but after few sec is back green again.
Same behavior if turning off via button on dps - it turns off for few sec and then automatically back on.
https://photos.app.goo.gl/REyUWzowwa91pwYRA

Expected would be that after outputEN=0 it stays off. 
My use case is for overvoltage protection - if any of lifepo4 cells above 3.6v then cutting off output. Temporary workaround - using currentcap=0 and then setting it back after safety period.

**Comment by rin67630** [comment]
IMHO you can't power off the DPS as long as it is back fed from the battery. (The current flows through to bypass diode of the FET  that you can't control)
You would need an ideal diode between the battery and the DPS. 
You will then lose communication overnight and only get it back when you have enough solar power to revive the DPS.
