### ISSUE TITLE
Could it work with an ESP01?

### ISSUE THREAD

**Issue by basaravia** [opensolarproject/OSPController#3]
As I can understand the main communication protocol is UART, and the ESP8266 (ESP01) easily handle that , it will cost less and can be more portable.

**Comment by t413** [comment]
Sadly the ESP01 doesn't have an ADC and we need one to measure the solar panel input voltage.

An ESP8266 has one ADC channel with 10bit resolution so it may work, but the little extra resolution of the ESP32 and far more flexibility made it an easy choice. The ESP32 has 12 bit resolution (0-4096).
