### ISSUE TITLE
PlatformIO defects ... err say whaa? 

### ISSUE THREAD

**Issue by mrstuff** [opensolarproject/OSPController#9]
cppcheck | LOW | STYLE | CWE-398:Class 'PowerSupply' has a constructor with 1 argument that is not explicit. | …1/lib/MPPTLib/utils.h:12:5
-- | -- | -- | -- | --
cppcheck | LOW | STYLE | CWE-398:Class 'PubSubClient' has a constructor with 1 argument that is not explicit. | …src/PubSubClient.h:117:4
cppcheck | LOW | STYLE | CWE-0:The function 'write' overrides a function in a base class but is not marked with a 'override' specifier. | …src/PubSubClient.h:170:19
cppcheck | LOW | STYLE | CWE-0:The function 'write' overrides a function in a base class but is not marked with a 'override' specifier. | …src/PubSubClient.h:173:19

Translate???

**Comment by mrstuff** [comment]
I'm thinking I've just got something wrong on my end and it's a minor defect I expect

**Comment by t413** [comment]
These are just warnings, specifically style warnings somehow. 3/4 are in the MQTT library PubSubClient, the one is a strange one about my PowerSupply class that, yeah, makes no sense that it'd be even a style warning. Odd. 

Ignore! Also how did you generate these?
